(define-module (pache-packages)
  #:use-module (gnu packages)
  #:use-module (gnu system)
  #:export (default-applications system-packages))

(define default-applications
  (list (specification->package "emacs")
        (specification->package "emacs-exwm")
        (specification->package "git")
        (specification->package "mpv")
        (specification->package "rhythmbox")
        (specification->package "kitty")
        (specification->package "qbittorrent")
        (specification->package "nicotine+")
        (specification->package "ripgrep")
        (specification->package "zip")
        (specification->package "unzip")
        (specification->package "pulsemixer")
        (specification->package "xrandr")
        (specification->package "btop")
        (specification->package "gimp")
        (specification->package "feh")
        (specification->package "picom")
        (specification->package "font-iosevka")
        (specification->package "setxkbmap")
        (specification->package "xdg-utils")
        (specification->package "htop")
        (specification->package "atop")
        (specification->package "emacs-desktop-environment")))

(define system-packages
  (append default-applications
          %base-packages))
